#!/usr/bin/env python3
"""Create vR.P.41 notebook from P.40.3 template."""
import json, copy, sys

BASE = 'vR.P.40.3 Image Detection and Localisation.ipynb'
OUT  = 'vR.P.41 Image Detection and Localisation.ipynb'

with open(BASE, 'r', encoding='utf-8') as f:
    nb = json.load(f)
nb = copy.deepcopy(nb)

# ==== CELL 0: Title ====
nb['cells'][0]['source'] = [
    "# vR.P.41 \u2014 Image Tampering Detection and Localization\n",
    "## Unified Inception V1+V2+V3 custom encoder + Multi-Q RGB ELA (9ch)\n",
    "\n",
    "---\n",
    "\n",
    "| Field | Value |\n",
    "|-------|-------|\n",
    "| **Version** | vR.P.41 |\n",
    "| **Track** | Pretrained Localization (Track 2) |\n",
    "| **Architecture** | UNet with Unified Inception V1+V2+V3 Custom (from scratch) |\n",
    "| **Change** | Unified Inception V1+V2+V3 custom encoder + Multi-Q RGB ELA (9ch) |\n",
    "| **Parent** | vR.P.30.1 |\n",
    "| **Dataset** | CASIA v2.0 \u2014 Splicing Detection + Localization (~12,614 images + GT masks) |\n",
    "| **Platform** | Kaggle (T4/P100 GPU) |\n",
    "| **Framework** | PyTorch + Segmentation Models PyTorch (SMP) |\n",
    "\n",
    "---\n",
    "\n",
    "### Pipeline Overview\n",
    "\n",
    "```\n",
    "Raw RGB Image\n",
    "    |\n",
    "    v\n",
    "Multi-Quality RGB ELA Preprocessing (9ch)\n",
    "    |-- JPEG recompress at Q=75 -> RGB ELA -> Channels 0\u20132\n",
    "    |-- JPEG recompress at Q=85 -> RGB ELA -> Channels 3\u20135\n",
    "    |-- JPEG recompress at Q=95 -> RGB ELA -> Channels 6\u20138\n",
    "    |\n",
    "    v\n",
    "Unified Inception V1+V2+V3 Encoder (from scratch)\n",
    "    |-- Stage 0: Input (9ch)\n",
    "    |-- Stage 1: Stem Conv(32, stride=2) + BN -> 32ch\n",
    "    |-- Stage 2: 2x InceptionV1 (classic, no BN) -> 240ch\n",
    "    |-- Stage 3: 2x InceptionV2 (factorized 5x5, BN) -> 256ch\n",
    "    |-- Stage 4: 2x InceptionV3 (asymmetric 1xN/Nx1, BN) -> 256ch\n",
    "    |-- Stage 5: 1x InceptionV3 (n=5) -> 416ch\n",
    "    |\n",
    "    v\n",
    "UNet Decoder (5 stages, skip connections from encoder)\n",
    "    |\n",
    "    v\n",
    "Sigmoid \u2192 384x384 Binary Mask\n",
    "```\n",
    "\n",
    "### Architecture Provenance\n",
    "Ported from **Hitansh Inception DeepFake notebook** (TensorFlow/Keras) to PyTorch + SMP.\n",
    "- Original: binary classification with GAP skip connections\n",
    "- Ported: pixel-level segmentation with spatial skip connections via UNet\n",
    "- Input: 9ch Multi-Q RGB ELA instead of 3ch RGB\n",
    "\n",
    "### Input\n",
    "- **Multi-Q RGB ELA \u2192 9-Channel (Q=75/85/95 \u00d7 R/G/B)**"
]

# ==== CELL 1: Changelog ====
nb['cells'][1]['source'] = [
    "---\n",
    "\n",
    "## Change Log\n",
    "\n",
    "| Version | Track | Change | Result |\n",
    "|---------|-------|--------|--------|\n",
    "| vR.P.3 | Pretrained | ELA as input Q=90 (replace RGB), frozen+BN | Pixel F1 = 0.6920 |\n",
    "| vR.P.10 | Pretrained | CBAM attention + Focal+Dice | Pixel F1 = 0.7277 |\n",
    "| vR.P.15 | Pretrained | Multi-quality ELA (Q=75/85/95) grayscale | Pixel F1 = 0.7329 |\n",
    "| vR.P.19 | Pretrained | Multi-quality RGB ELA (9ch, Q=75/85/95) | Pixel F1 = 0.7965 |\n",
    "| vR.P.30.1 | Pretrained | Multi-Q ELA + CBAM (50ep, BCE+Dice) | Pixel F1 = TBD |\n",
    "| vR.P.40.1 | Pretrained | EfficientNet-B4 baseline (ELA Q=90, 3ch) | TBD |\n",
    "| vR.P.40.2 | Pretrained | EfficientNet-B4 + Multi-Q RGB ELA (9ch) | TBD |\n",
    "| vR.P.40.3 | Pretrained | InceptionV1 custom encoder + MQ-RGB-ELA 9ch | TBD |\n",
    "| vR.P.40.4 | Pretrained | InceptionV2 custom encoder + MQ-RGB-ELA 9ch | TBD |\n",
    "| vR.P.40.5 | Pretrained | InceptionV3 custom encoder + MQ-RGB-ELA 9ch | TBD |\n",
    "| **vR.P.41** | Pretrained | **Unified Inception V1+V2+V3 custom encoder + MQ-RGB-ELA 9ch** | **TBD** |"
]

# ==== CELL 2: Config (modify constants) ====
cell2_lines = nb['cells'][2]['source']
replacements = {
    "VERSION = 'vR.P.40.3'": "VERSION = 'vR.P.41'",
    "CHANGE = 'InceptionV1 custom encoder + Multi-Q RGB ELA (9ch)'":
        "CHANGE = 'Unified Inception V1+V2+V3 custom encoder + Multi-Q RGB ELA (9ch)'",
    "BATCH_SIZE = 8": "BATCH_SIZE = 16",
    "ENCODER = 'inception-v1-custom'": "ENCODER = 'unified-inception-v123'",
    "LEARNING_RATE = 0.001": "LEARNING_RATE = 1e-4",
    "EPOCHS = 30": "EPOCHS = 50",
}
for i, line in enumerate(cell2_lines):
    for old, new in replacements.items():
        if old in line:
            cell2_lines[i] = line.replace(old, new)

# ==== CELL 12: Encoder (KEY CELL) ====
nb['cells'][12]['source'] = [
    "# ============================================================\n",
    "# 4.1 Custom Unified Inception V1+V2+V3 Encoder + SMP Registration\n",
    "# ============================================================\n",
    "\n",
    "# --- InceptionV1 Module (Classic GoogLeNet, no BN) ---\n",
    "class InceptionV1Module(nn.Module):\n",
    '    """Classic Inception V1: 4 parallel branches (no BN). Ported from Hitansh notebook."""\n',
    "    def __init__(self, in_ch, f1, f3r, f3, f5r, f5, fpool):\n",
    "        super().__init__()\n",
    "        self.branch1 = nn.Sequential(\n",
    "            nn.Conv2d(in_ch, f1, 1), nn.ReLU(inplace=True))\n",
    "        self.branch2 = nn.Sequential(\n",
    "            nn.Conv2d(in_ch, f3r, 1), nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(f3r, f3, 3, padding=1), nn.ReLU(inplace=True))\n",
    "        self.branch3 = nn.Sequential(\n",
    "            nn.Conv2d(in_ch, f5r, 1), nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(f5r, f5, 5, padding=2), nn.ReLU(inplace=True))\n",
    "        self.branch4 = nn.Sequential(\n",
    "            nn.MaxPool2d(3, stride=1, padding=1),\n",
    "            nn.Conv2d(in_ch, fpool, 1), nn.ReLU(inplace=True))\n",
    "        self.out_channels = f1 + f3 + f5 + fpool\n",
    "\n",
    "    def forward(self, x):\n",
    "        return torch.cat([self.branch1(x), self.branch2(x),\n",
    "                         self.branch3(x), self.branch4(x)], dim=1)\n",
    "\n",
    "\n",
    "# --- InceptionV2 Module (Factorized 5x5 -> two 3x3, BN, AvgPool) ---\n",
    "class InceptionV2Module(nn.Module):\n",
    '    """Inception V2: factorized 5x5 into two 3x3, BatchNorm, AvgPool. Ported from Hitansh notebook."""\n',
    "    def __init__(self, in_ch, f1, f3r, f3, fdr, fd, fpool):\n",
    "        super().__init__()\n",
    "        self.branch1 = nn.Sequential(\n",
    "            nn.Conv2d(in_ch, f1, 1, bias=False), nn.BatchNorm2d(f1), nn.ReLU(inplace=True))\n",
    "        self.branch2 = nn.Sequential(\n",
    "            nn.Conv2d(in_ch, f3r, 1, bias=False), nn.BatchNorm2d(f3r), nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(f3r, f3, 3, padding=1, bias=False), nn.BatchNorm2d(f3), nn.ReLU(inplace=True))\n",
    "        # Factorized 5x5 -> two 3x3\n",
    "        self.branch3 = nn.Sequential(\n",
    "            nn.Conv2d(in_ch, fdr, 1, bias=False), nn.BatchNorm2d(fdr), nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(fdr, fd, 3, padding=1, bias=False), nn.BatchNorm2d(fd), nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(fd, fd, 3, padding=1, bias=False), nn.BatchNorm2d(fd), nn.ReLU(inplace=True))\n",
    "        self.branch4 = nn.Sequential(\n",
    "            nn.AvgPool2d(3, stride=1, padding=1),\n",
    "            nn.Conv2d(in_ch, fpool, 1, bias=False), nn.BatchNorm2d(fpool), nn.ReLU(inplace=True))\n",
    "        self.out_channels = f1 + f3 + fd + fpool\n",
    "\n",
    "    def forward(self, x):\n",
    "        return torch.cat([self.branch1(x), self.branch2(x),\n",
    "                         self.branch3(x), self.branch4(x)], dim=1)\n",
    "\n",
    "\n",
    "# --- InceptionV3 Module (Asymmetric 1xN + Nx1 factorization, BN) ---\n",
    "class InceptionV3Module(nn.Module):\n",
    '    """Inception V3: asymmetric 1xN + Nx1 factorization, BatchNorm.\n',
    "    Ported from Hitansh Inception DeepFake notebook.\n",
    '    Branches: b1=1x1, b2=1x1->1xN->Nx1, b3=1x1->1xN->Nx1->1xN->Nx1, b4=AvgPool->1x1."""\n',
    "    def __init__(self, in_ch, f1, f3r, f3, fdr, fd, fpool, n=7):\n",
    "        super().__init__()\n",
    "        self.branch1 = nn.Sequential(\n",
    "            nn.Conv2d(in_ch, f1, 1, bias=False), nn.BatchNorm2d(f1), nn.ReLU(inplace=True))\n",
    "        # Single asymmetric: 1x1 -> 1xN -> Nx1\n",
    "        self.branch2 = nn.Sequential(\n",
    "            nn.Conv2d(in_ch, f3r, 1, bias=False), nn.BatchNorm2d(f3r), nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(f3r, f3, (1, n), padding=(0, n // 2), bias=False),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(f3, f3, (n, 1), padding=(n // 2, 0), bias=False),\n",
    "            nn.BatchNorm2d(f3), nn.ReLU(inplace=True))\n",
    "        # Double asymmetric: 1x1 -> 1xN -> Nx1 -> 1xN -> Nx1\n",
    "        self.branch3 = nn.Sequential(\n",
    "            nn.Conv2d(in_ch, fdr, 1, bias=False), nn.BatchNorm2d(fdr), nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(fdr, fd, (1, n), padding=(0, n // 2), bias=False),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(fd, fd, (n, 1), padding=(n // 2, 0), bias=False),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(fd, fd, (1, n), padding=(0, n // 2), bias=False),\n",
    "            nn.ReLU(inplace=True),\n",
    "            nn.Conv2d(fd, fd, (n, 1), padding=(n // 2, 0), bias=False),\n",
    "            nn.BatchNorm2d(fd), nn.ReLU(inplace=True))\n",
    "        self.branch4 = nn.Sequential(\n",
    "            nn.AvgPool2d(3, stride=1, padding=1),\n",
    "            nn.Conv2d(in_ch, fpool, 1, bias=False), nn.BatchNorm2d(fpool), nn.ReLU(inplace=True))\n",
    "        self.out_channels = f1 + f3 + fd + fpool\n",
    "\n",
    "    def forward(self, x):\n",
    "        return torch.cat([self.branch1(x), self.branch2(x),\n",
    "                         self.branch3(x), self.branch4(x)], dim=1)\n",
    "\n",
    "\n",
    "# --- Unified Inception V1+V2+V3 Encoder ---\n",
    "from segmentation_models_pytorch.encoders._base import EncoderMixin\n",
    "\n",
    "class UnifiedInceptionEncoder(nn.Module, EncoderMixin):\n",
    '    """5-stage encoder using progressive Inception V1 -> V2 -> V3 modules.\n',
    "    Ported from Hitansh 'Unified Inception V1+V2+V3 Slim' architecture.\n",
    "    Original: classification with GAP skip connections.\n",
    "    Ported: segmentation encoder with spatial feature maps for UNet decoder.\n",
    "\n",
    "    Stage layout:\n",
    "      Stage 0: Input (9ch, 384x384)\n",
    "      Stage 1: Stem Conv(32, stride=2) + BN -> 32ch, 192x192\n",
    "      Stage 2: 2x InceptionV1 + MaxPool -> 240ch, 96x96\n",
    "      Stage 3: 2x InceptionV2 + MaxPool -> 256ch, 48x48\n",
    "      Stage 4: 2x InceptionV3(n=3) + MaxPool -> 256ch, 24x24\n",
    '      Stage 5: 1x InceptionV3(n=5) + MaxPool -> 416ch, 12x12"""\n',
    "\n",
    "    def __init__(self, in_channels=9, depth=5, **kwargs):\n",
    "        super().__init__()\n",
    "        self._depth = depth\n",
    "        self._in_channels = in_channels\n",
    "        self._out_channels = [in_channels, 32, 240, 256, 256, 416]\n",
    "\n",
    "        # Stage 1: Stem\n",
    "        self.stem = nn.Sequential(\n",
    "            nn.Conv2d(in_channels, 32, 3, stride=2, padding=1, bias=False),\n",
    "            nn.BatchNorm2d(32),\n",
    "            nn.ReLU(inplace=True))\n",
    "\n",
    "        # Stage 2: Inception V1 (classic, no BN) -- 2 modules + MaxPool\n",
    "        self.v1_m1 = InceptionV1Module(32, 32, 48, 64, 8, 16, 16)    # out=128\n",
    "        self.v1_m2 = InceptionV1Module(128, 64, 64, 96, 16, 48, 32)  # out=240\n",
    "        self.pool2 = nn.MaxPool2d(2, 2)\n",
    "\n",
    "        # Stage 3: Inception V2 (factorized, BN) -- 2 modules + MaxPool\n",
    "        self.v2_m1 = InceptionV2Module(240, 96, 48, 104, 8, 24, 32)   # out=256\n",
    "        self.v2_m2 = InceptionV2Module(256, 80, 56, 112, 12, 32, 32)  # out=256\n",
    "        self.pool3 = nn.MaxPool2d(2, 2)\n",
    "\n",
    "        # Stage 4: Inception V3 (asymmetric, BN) -- 2 modules(n=3) + MaxPool\n",
    "        self.v3_m1 = InceptionV3Module(256, 96, 48, 104, 8, 24, 32, n=3)   # out=256\n",
    "        self.v3_m2 = InceptionV3Module(256, 80, 56, 112, 12, 32, 32, n=3)  # out=256\n",
    "        self.pool4 = nn.MaxPool2d(2, 2)\n",
    "\n",
    "        # Stage 5: Inception V3 (wider, n=5) -- 1 module + MaxPool\n",
    "        self.v3_m3 = InceptionV3Module(256, 128, 80, 160, 16, 64, 64, n=5)  # out=416\n",
    "        self.pool5 = nn.MaxPool2d(2, 2)\n",
    "\n",
    "    @property\n",
    "    def out_channels(self):\n",
    "        return self._out_channels[:self._depth + 1]\n",
    "\n",
    "    def forward(self, x):\n",
    "        features = [x]                          # Stage 0: input (9, 384, 384)\n",
    "\n",
    "        x = self.stem(x)                        # Stage 1: (32, 192, 192)\n",
    "        features.append(x)\n",
    "\n",
    "        x = self.v1_m1(x)                       # (128, 192, 192)\n",
    "        x = self.v1_m2(x)                       # (240, 192, 192)\n",
    "        x = self.pool2(x)                       # (240, 96, 96)\n",
    "        features.append(x)                      # Stage 2\n",
    "\n",
    "        x = self.v2_m1(x)                       # (256, 96, 96)\n",
    "        x = self.v2_m2(x)                       # (256, 96, 96)\n",
    "        x = self.pool3(x)                       # (256, 48, 48)\n",
    "        features.append(x)                      # Stage 3\n",
    "\n",
    "        x = self.v3_m1(x)                       # (256, 48, 48)\n",
    "        x = self.v3_m2(x)                       # (256, 48, 48)\n",
    "        x = self.pool4(x)                       # (256, 24, 24)\n",
    "        features.append(x)                      # Stage 4\n",
    "\n",
    "        x = self.v3_m3(x)                       # (416, 24, 24)\n",
    "        x = self.pool5(x)                       # (416, 12, 12)\n",
    "        features.append(x)                      # Stage 5\n",
    "\n",
    "        return features[:self._depth + 1]\n",
    "\n",
    "    def set_in_channels(self, in_channels, pretrained=False):\n",
    '        """Override SMP default to avoid patch_first_conv on custom architecture."""\n',
    "        if in_channels == self._in_channels:\n",
    "            return\n",
    "        self._in_channels = in_channels\n",
    "        self._out_channels = [in_channels] + list(self._out_channels[1:])\n",
    "        self.stem[0] = nn.Conv2d(in_channels, 32, 3, stride=2, padding=1, bias=False)\n",
    "\n",
    "    def load_state_dict(self, state_dict, **kwargs):\n",
    "        super().load_state_dict(state_dict, strict=False)\n",
    "\n",
    "\n",
    "# Register with SMP\n",
    "smp.encoders.encoders['unified-inception-v123'] = {\n",
    "    'encoder': UnifiedInceptionEncoder,\n",
    "    'pretrained_settings': {},\n",
    "    'params': {'in_channels': IN_CHANNELS, 'depth': 5}\n",
    "}\n",
    "\n",
    "model = smp.Unet(\n",
    "    encoder_name='unified-inception-v123',\n",
    "    encoder_weights=None,\n",
    "    in_channels=IN_CHANNELS,\n",
    "    classes=NUM_CLASSES,\n",
    "    decoder_channels=DECODER_CHANNELS,\n",
    "    activation=None\n",
    ")\n",
    "model = model.to(DEVICE)\n",
    "\n",
    "total_params = sum(p.numel() for p in model.parameters())\n",
    "trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
    "\n",
    "print(f'Model: UNet + Unified Inception V1+V2+V3 Encoder (from scratch)')\n",
    "print(f'  Encoder out_channels: {UnifiedInceptionEncoder(in_channels=IN_CHANNELS)._out_channels}')\n",
    "print(f'  V1 stages: 2 modules (no BN, classic GoogLeNet)')\n",
    "print(f'  V2 stages: 2 modules (factorized 5x5, BN)')\n",
    "print(f'  V3 stages: 3 modules (asymmetric 1xN/Nx1, BN)')\n",
    "print(f'Total parameters:     {total_params:>12,}')\n",
    "print(f'Trainable parameters: {trainable_params:>12,} (100% \\u2014 no pretrained weights)')"
]

# ==== CELL 14: Loss, Optimizer ====
nb['cells'][14]['source'] = [
    "# ============================================================\n",
    "# 5.1 Loss, Optimizer, Scheduler (All Trainable \u2014 From Scratch)\n",
    "# ============================================================\n",
    "\n",
    "bce_loss_fn = smp.losses.SoftBCEWithLogitsLoss()\n",
    "dice_loss_fn = smp.losses.DiceLoss(mode='binary', from_logits=True)\n",
    "\n",
    "def criterion(pred, target):\n",
    "    return bce_loss_fn(pred, target) + dice_loss_fn(pred, target)\n",
    "\n",
    "# All params trainable \u2014 no frozen encoder\n",
    "optimizer = optim.AdamW(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-5)\n",
    "\n",
    "print(f'Optimizer: AdamW (LR={LEARNING_RATE}, weight_decay=1e-5)')\n",
    "print(f'  Total trainable: {sum(p.numel() for p in model.parameters()):,}')\n",
    "\n",
    "scheduler = optim.lr_scheduler.ReduceLROnPlateau(\n",
    "    optimizer, mode='min', factor=0.5, patience=3)"
]

# ==== CELL 25: Results Table ====
nb['cells'][25]['source'] = [
    "# ============================================================\n",
    "# 8.1 Results Tracking Table\n",
    "# ============================================================\n",
    "\n",
    "print(f'{\"=\"*100}')\n",
    "print(f'  RESULTS SUMMARY \u2014 vR.P.41')\n",
    "print(f'{\"=\"*100}')\n",
    "print()\n",
    "\n",
    "print('Cross-Track Comparison:')\n",
    "print(f'{\"Version\":<12} {\"Track\":<12} {\"Encoder\":<26} {\"Input\":<18} '\n",
    "      f'{\"Pixel-F1\":<10} {\"IoU\":<8}')\n",
    "print('-' * 94)\n",
    "\n",
    "print(f'{\"vR.P.3\":<12} {\"Pretrained\":<12} {\"ResNet-34\":<26} {\"ELA Q90\":<18} '\n",
    "      f'{\"0.6920\":<10} {\"0.5291\":<8}')\n",
    "print(f'{\"vR.P.10\":<12} {\"Pretrained\":<12} {\"ResNet-34\":<26} {\"ELA+CBAM\":<18} '\n",
    "      f'{\"0.7277\":<10} {\"0.5719\":<8}')\n",
    "print(f'{\"vR.P.19\":<12} {\"Pretrained\":<12} {\"ResNet-34\":<26} {\"MQ-RGB-ELA 9ch\":<18} '\n",
    "      f'{\"0.7965\":<10} {\"0.6622\":<8}')\n",
    "print(f'{\"vR.P.40.3\":<12} {\"Pretrained\":<12} {\"inception-v1-custom\":<26} '\n",
    "      f'{\"MQ-RGB-ELA 9ch\":<18} {\"TBD\":<10} {\"TBD\":<8}')\n",
    "print(f'{\"vR.P.40.4\":<12} {\"Pretrained\":<12} {\"inception-v2-custom\":<26} '\n",
    "      f'{\"MQ-RGB-ELA 9ch\":<18} {\"TBD\":<10} {\"TBD\":<8}')\n",
    "print(f'{\"vR.P.40.5\":<12} {\"Pretrained\":<12} {\"inception-v3-custom\":<26} '\n",
    "      f'{\"MQ-RGB-ELA 9ch\":<18} {\"TBD\":<10} {\"TBD\":<8}')\n",
    "\n",
    "# This run\n",
    "print(f'{\"vR.P.41\":<12} {\"Pretrained\":<12} {\"unified-inception-v123\":<26} '\n",
    "      f'{\"MQ-RGB-ELA 9ch\":<18} '\n",
    "      f'{pixel_f1:<10.4f} {pixel_iou:<8.4f}')\n",
    "print()\n",
    "\n",
    "print(f'Pixel-Level Metrics:')\n",
    "print(f'  Pixel F1 (Dice): {pixel_f1:.4f}')\n",
    "print(f'  Pixel IoU:       {pixel_iou:.4f}')\n",
    "print(f'  Pixel Precision: {pixel_precision:.4f}')\n",
    "print(f'  Pixel Recall:    {pixel_recall:.4f}')\n",
    "print(f'  Pixel AUC:       {pixel_auc:.4f}')\n",
    "print()\n",
    "print(f'Image-Level Metrics:')\n",
    "print(f'  Accuracy:        {cls_accuracy:.4f} ({cls_accuracy*100:.2f}%)')\n",
    "print(f'  Macro F1:        {cls_macro_f1:.4f}')\n",
    "print(f'  ROC-AUC:         {cls_auc:.4f}')"
]

# ==== CELL 26: Discussion ====
nb['cells'][26]['source'] = [
    "---\n",
    "\n",
    "## 9. Discussion\n",
    "\n",
    "### What Changed in vR.P.41\n",
    "\n",
    "**Unified Inception V1+V2+V3 encoder trained from scratch**\n",
    "- Progressive multi-generation architecture: V1 (early) \u2192 V2 (mid) \u2192 V3 (deep stages)\n",
    "- Combines three Inception generations in one encoder for complementary feature extraction\n",
    "- Ported from Hitansh Inception DeepFake notebook (TensorFlow/Keras) to PyTorch + SMP\n",
    "\n",
    "### Architecture Design\n",
    "- **V1 stages** (Stage 2): Classic 4-branch parallel (1x1, 3x3, 5x5, MaxPool), no BN\n",
    "- **V2 stages** (Stage 3): Factorized 5x5 into two 3x3, BatchNorm, AvgPool branch\n",
    "- **V3 stages** (Stages 4\u20135): Asymmetric 1xN + Nx1 factorization, BatchNorm\n",
    "- Filter counts preserved exactly from Hitansh reference\n",
    "\n",
    "### Key Differences from P.40.3/P.40.4/P.40.5\n",
    "- Those use a single Inception type (V1 or V2 or V3) across all stages\n",
    "- P.41 uses the *correct* historical progression: V1 \u2192 V2 \u2192 V3\n",
    "- Tests whether combining all three types provides complementary features\n",
    "\n",
    "### Expected Outcome\n",
    "- Richer feature extraction from progressive multi-scale + multi-factorization\n",
    "- Likely stronger than single-type encoders (P.40.3\u201340.5)\n",
    "- Still from scratch (no pretrained weights), so compare fairly against P.40.x series"
]

# ==== CELL 27: Save Model ====
nb['cells'][27]['source'] = [
    "# ============================================================\n",
    "# 10. Save Model\n",
    "# ============================================================\n",
    "\n",
    "model_filename = f'{VERSION}_unet_unified_inception_model.pth'\n",
    "torch.save({\n",
    "    'model_state_dict': model.state_dict(),\n",
    "    'optimizer_state_dict': optimizer.state_dict(),\n",
    "    'scheduler_state_dict': scheduler.state_dict(),\n",
    "    'best_epoch': best_epoch,\n",
    "    'best_val_loss': best_val_loss,\n",
    "    'history': history,\n",
    "    'config': {\n",
    "        'version': VERSION, 'encoder': ENCODER,\n",
    "        'architecture': 'UNet-UnifiedInceptionV123',\n",
    "        'image_size': IMAGE_SIZE, 'batch_size': BATCH_SIZE,\n",
    "        'learning_rate': LEARNING_RATE, 'ela_qualities': ELA_QUALITIES,\n",
    "        'in_channels': IN_CHANNELS, 'epochs_trained': len(history['train_loss']),\n",
    "        'seed': SEED,\n",
    "    }\n",
    "}, model_filename)\n",
    "\n",
    "print(f'Model saved: {model_filename}')\n",
    "print(f'File size: {os.path.getsize(model_filename) / 1e6:.1f} MB')\n",
    "print(f'\\n{VERSION} complete.')\n",
    "\n",
    "# --- Save Experiment Artifacts ---\n",
    "import json as _json\n",
    "from datetime import datetime as _dt\n",
    "\n",
    "_metrics = {\n",
    "    'version': VERSION,\n",
    "    'best_epoch': best_epoch,\n",
    "    'best_val_loss': float(best_val_loss),\n",
    "    'epochs_trained': len(history['train_loss']),\n",
    "    'history': {k: [float(v) for v in vals] for k, vals in history.items()},\n",
    "}\n",
    "with open(os.path.join(RESULTS_DIR, f'{VERSION}_metrics.json'), 'w') as _f:\n",
    "    _json.dump(_metrics, _f, indent=2)\n",
    "print(f'Metrics saved to {RESULTS_DIR}/{VERSION}_metrics.json')\n",
    "\n",
    "if USE_WANDB:\n",
    "    try:\n",
    "        wandb.log({\n",
    "            'pixel_f1': pixel_f1, 'pixel_iou': pixel_iou,\n",
    "            'pixel_precision': pixel_precision, 'pixel_recall': pixel_recall,\n",
    "            'pixel_auc': pixel_auc, 'cls_accuracy': cls_accuracy,\n",
    "            'cls_macro_f1': cls_macro_f1, 'cls_auc': cls_auc,\n",
    "            'best_epoch': best_epoch, 'best_val_loss': best_val_loss,\n",
    "        })\n",
    "        wandb.finish()\n",
    "        print('W&B run finished.')\n",
    "    except Exception as e:\n",
    "        print(f'W&B finish warning: {e}')"
]

# ==== WRITE ====
with open(OUT, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)
    f.write('\n')

print(f'Created: {OUT}')
print(f'Total cells: {len(nb["cells"])}')
