"""Build tamper_detection_v3.ipynb programmatically."""
import json

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source}

def code(source):
    return {"cell_type": "code", "metadata": {}, "source": source, "execution_count": None, "outputs": []}

cells = []

# ============================================================
# TITLE
# ============================================================
cells.append(md([
    "# Tampered Image Detection & Localization (v3)\n",
    "\n",
    "**Task:** Given an image, (1) classify it as tampered or authentic, and (2) produce a pixel-level binary mask localizing tampered regions.\n",
    "\n",
    "**Approach:** U-Net with pretrained ResNet34 encoder on CASIA v2.0, BCE + Dice loss, AMP training, validation-based threshold, mixed-set + tampered-only evaluation.\n",
    "\n",
    "**Environment:** Google Colab — T4 GPU\n",
    "\n",
    "---\n",
    "\n",
    "### Notebook Sections\n",
    "\n",
    "| # | Section |\n",
    "|---|---|\n",
    "| 1 | Setup & Environment |\n",
    "| 2 | Dataset Download & Discovery |\n",
    "| 3 | Preprocessing & Data Split |\n",
    "| 4 | Dataset Class & DataLoaders |\n",
    "| 5 | Model Definition |\n",
    "| 6 | Loss Function & Optimizer |\n",
    "| 7 | Metrics |\n",
    "| 8 | Training Loop |\n",
    "| 9 | Threshold Selection |\n",
    "| 10 | Evaluation |\n",
    "| 11 | Visualization |\n",
    "| 12 | Robustness Testing (Bonus) |\n",
    "| 13 | Experiment Tracking (Optional) |\n",
    "| 14 | Save & Export |\n",
    "\n",
    "**Changes from v1:** See Docs3/00_Master_Report.md for the full diff."
]))

# ============================================================
# 1. SETUP
# ============================================================
cells.append(md([
    "---\n",
    "## 1. Setup & Environment\n",
    "\n",
    "Install all dependencies (including `kaggle`), set seed, verify GPU."
]))

cells.append(code([
    "# ── Install dependencies ──────────────────────────────────────────────\n",
    "!pip install -q kaggle segmentation-models-pytorch \"albumentations>=1.3.1,<2.0\""
]))

cells.append(code([
    "# ── Imports ───────────────────────────────────────────────────────────\n",
    "import os\n",
    "import random\n",
    "import json\n",
    "import warnings\n",
    "from pathlib import Path\n",
    "\n",
    "import numpy as np\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "from torch.amp import autocast, GradScaler\n",
    "\n",
    "import segmentation_models_pytorch as smp\n",
    "import albumentations as A\n",
    "from albumentations.pytorch import ToTensorV2\n",
    "\n",
    "import cv2\n",
    "from PIL import Image\n",
    "import matplotlib.pyplot as plt\n",
    "from tqdm import tqdm\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import roc_auc_score, roc_curve, auc\n",
    "\n",
    "warnings.filterwarnings('ignore')\n",
    "print(f\"PyTorch {torch.__version__}\")\n",
    "print(f\"SMP {smp.__version__}\")\n",
    "print(f\"Albumentations {A.__version__}\")"
]))

cells.append(code([
    "# ── Reproducibility ──────────────────────────────────────────────────\n",
    "SEED = 42\n",
    "\n",
    "def set_seed(seed=SEED):\n",
    "    random.seed(seed)\n",
    "    np.random.seed(seed)\n",
    "    torch.manual_seed(seed)\n",
    "    torch.cuda.manual_seed_all(seed)\n",
    "    torch.backends.cudnn.deterministic = True\n",
    "    torch.backends.cudnn.benchmark = False\n",
    "\n",
    "set_seed()"
]))

cells.append(code([
    "# ── GPU verification ─────────────────────────────────────────────────\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"Device: {device}\")\n",
    "if torch.cuda.is_available():\n",
    "    print(f\"GPU: {torch.cuda.get_device_name()}\")\n",
    "    vram = torch.cuda.get_device_properties(0).total_mem / 1e9\n",
    "    print(f\"VRAM: {vram:.1f} GB\")\n",
    "else:\n",
    "    print(\"WARNING: No GPU detected. Go to Runtime > Change runtime type > GPU.\")"
]))

cells.append(code([
    "# ── Configuration ────────────────────────────────────────────────────\n",
    "CONFIG = {\n",
    "    # Data\n",
    "    'image_size': 512,\n",
    "    'batch_size': 4,\n",
    "    'num_workers': 2,\n",
    "    'train_ratio': 0.85,\n",
    "    # Model\n",
    "    'encoder_name': 'resnet34',\n",
    "    'encoder_weights': 'imagenet',\n",
    "    'in_channels': 3,\n",
    "    'classes': 1,\n",
    "    # Training\n",
    "    'encoder_lr': 1e-4,\n",
    "    'decoder_lr': 1e-3,\n",
    "    'weight_decay': 1e-4,\n",
    "    'max_epochs': 50,\n",
    "    'patience': 10,\n",
    "    'accumulation_steps': 4,\n",
    "    'max_grad_norm': 1.0,\n",
    "    # Eval\n",
    "    'default_threshold': 0.5,\n",
    "    'n_threshold_search': 50,\n",
    "    # Paths\n",
    "    'data_dir': './data',\n",
    "    'checkpoint_dir': './checkpoints',\n",
    "}\n",
    "\n",
    "# ── Google Drive persistence (set True in Colab) ─────────────────────\n",
    "USE_DRIVE = False\n",
    "if USE_DRIVE:\n",
    "    from google.colab import drive\n",
    "    drive.mount('/content/drive')\n",
    "    CONFIG['checkpoint_dir'] = '/content/drive/MyDrive/tamper_detection/checkpoints'\n",
    "\n",
    "os.makedirs(CONFIG['checkpoint_dir'], exist_ok=True)\n",
    "print(\"Configuration:\")\n",
    "for k, v in CONFIG.items():\n",
    "    print(f\"  {k}: {v}\")"
]))

# ============================================================
# 2. DATASET DOWNLOAD & DISCOVERY
# ============================================================
cells.append(md([
    "---\n",
    "## 2. Dataset Download & Discovery\n",
    "\n",
    "Download CASIA v2.0 via Kaggle API. Discover image-mask pairs dynamically and validate alignment.\n",
    "\n",
    "**v3 change:** Discovery function now returns `(pairs, excluded)` tuple. Forgery type has a guard for unrecognized patterns."
]))

cells.append(code([
    "# ── Kaggle download ──────────────────────────────────────────────────\n",
    "# Set credentials — prefer Colab Secrets for security\n",
    "# os.environ['KAGGLE_USERNAME'] = 'your_username'\n",
    "# os.environ['KAGGLE_KEY'] = 'your_api_key'\n",
    "\n",
    "DATASET_ROOT = os.path.join(CONFIG['data_dir'], 'CASIA2')\n",
    "\n",
    "if not os.path.exists(DATASET_ROOT):\n",
    "    !kaggle datasets download -d sophatvathana/casia-dataset -p {CONFIG['data_dir']}\n",
    "    !unzip -q {CONFIG['data_dir']}/casia-dataset.zip -d {CONFIG['data_dir']}\n",
    "    print(\"Dataset downloaded and extracted.\")\n",
    "else:\n",
    "    print(f\"Dataset already exists at {DATASET_ROOT}\")\n",
    "\n",
    "TP_DIR = os.path.join(DATASET_ROOT, 'Tp')\n",
    "GT_DIR = os.path.join(DATASET_ROOT, 'Gt')\n",
    "AU_DIR = os.path.join(DATASET_ROOT, 'Au')\n",
    "\n",
    "for d, name in [(TP_DIR, 'Tampered'), (GT_DIR, 'Ground Truth'), (AU_DIR, 'Authentic')]:\n",
    "    exists = os.path.isdir(d)\n",
    "    count = len(os.listdir(d)) if exists else 0\n",
    "    print(f\"  {name}: {d} — {'found' if exists else 'MISSING'} ({count} files)\")"
]))

cells.append(code([
    "# ── Dynamic pair discovery ────────────────────────────────────────────\n",
    "def validate_pair(image_path, mask_path):\n",
    "    \"\"\"Check that image and mask have the same spatial dimensions.\"\"\"\n",
    "    img = Image.open(image_path)\n",
    "    msk = Image.open(mask_path)\n",
    "    return img.size == msk.size\n",
    "\n",
    "\n",
    "def discover_pairs(dataset_root):\n",
    "    \"\"\"\n",
    "    Discover all valid image-mask pairs and authentic images.\n",
    "\n",
    "    Returns:\n",
    "        pairs: list of dicts {image_path, mask_path, label, forgery_type}\n",
    "        excluded: list of (filename, reason) tuples\n",
    "    \"\"\"\n",
    "    tp_dir = os.path.join(dataset_root, 'Tp')\n",
    "    gt_dir = os.path.join(dataset_root, 'Gt')\n",
    "    au_dir = os.path.join(dataset_root, 'Au')\n",
    "\n",
    "    pairs = []\n",
    "    excluded = []\n",
    "\n",
    "    # ── Tampered images ──\n",
    "    for img_name in sorted(os.listdir(tp_dir)):\n",
    "        img_path = os.path.join(tp_dir, img_name)\n",
    "        if not os.path.isfile(img_path):\n",
    "            continue\n",
    "        stem = Path(img_name).stem\n",
    "        mask_name = stem + '_gt.png'\n",
    "        mask_path = os.path.join(gt_dir, mask_name)\n",
    "\n",
    "        if not os.path.exists(mask_path):\n",
    "            excluded.append((img_name, 'mask_not_found'))\n",
    "            continue\n",
    "\n",
    "        if not validate_pair(img_path, mask_path):\n",
    "            excluded.append((img_name, 'dimension_mismatch'))\n",
    "            continue\n",
    "\n",
    "        # Forgery type with guard for unrecognized patterns\n",
    "        if '_D_' in stem:\n",
    "            forgery_type = 'splicing'\n",
    "        elif '_S_' in stem:\n",
    "            forgery_type = 'copy-move'\n",
    "        else:\n",
    "            forgery_type = 'unknown'\n",
    "            warnings.warn(f\"Unrecognized forgery pattern in filename: {img_name}\")\n",
    "\n",
    "        pairs.append({\n",
    "            'image_path': img_path,\n",
    "            'mask_path': mask_path,\n",
    "            'label': 1.0,\n",
    "            'forgery_type': forgery_type,\n",
    "        })\n",
    "\n",
    "    # ── Authentic images ──\n",
    "    for img_name in sorted(os.listdir(au_dir)):\n",
    "        img_path = os.path.join(au_dir, img_name)\n",
    "        if not os.path.isfile(img_path):\n",
    "            continue\n",
    "        try:\n",
    "            img = Image.open(img_path)\n",
    "            img.verify()\n",
    "        except Exception:\n",
    "            excluded.append((img_name, 'corrupt_file'))\n",
    "            continue\n",
    "\n",
    "        pairs.append({\n",
    "            'image_path': img_path,\n",
    "            'mask_path': None,\n",
    "            'label': 0.0,\n",
    "            'forgery_type': 'authentic',\n",
    "        })\n",
    "\n",
    "    return pairs, excluded\n",
    "\n",
    "\n",
    "pairs, excluded = discover_pairs(DATASET_ROOT)\n",
    "\n",
    "# Report\n",
    "type_counts = {}\n",
    "for p in pairs:\n",
    "    t = p['forgery_type']\n",
    "    type_counts[t] = type_counts.get(t, 0) + 1\n",
    "\n",
    "print(f\"\\nTotal valid pairs: {len(pairs)}\")\n",
    "for t, c in sorted(type_counts.items()):\n",
    "    print(f\"  {t}: {c}\")\n",
    "\n",
    "print(f\"\\nExcluded: {len(excluded)}\")\n",
    "for name, reason in excluded[:20]:\n",
    "    print(f\"  {name}: {reason}\")\n",
    "if len(excluded) > 20:\n",
    "    print(f\"  ... and {len(excluded) - 20} more\")"
]))

# ============================================================
# 3. PREPROCESSING & SPLIT
# ============================================================
cells.append(md([
    "---\n",
    "## 3. Preprocessing & Data Split\n",
    "\n",
    "Stratified 85/7.5/7.5 split by forgery type. Manifest persisted for reproducibility."
]))

cells.append(code([
    "# ── Stratified split ─────────────────────────────────────────────────\n",
    "labels_for_split = [p['forgery_type'] for p in pairs]\n",
    "\n",
    "# Step 1: train (85%) vs temp (15%)\n",
    "train_pairs, temp_pairs = train_test_split(\n",
    "    pairs, test_size=0.15, random_state=SEED, stratify=labels_for_split\n",
    ")\n",
    "\n",
    "# Step 2: temp → val (50%) + test (50%)\n",
    "temp_labels = [p['forgery_type'] for p in temp_pairs]\n",
    "val_pairs, test_pairs = train_test_split(\n",
    "    temp_pairs, test_size=0.5, random_state=SEED, stratify=temp_labels\n",
    ")\n",
    "\n",
    "print(f\"Train: {len(train_pairs)}\")\n",
    "print(f\"Val:   {len(val_pairs)}\")\n",
    "print(f\"Test:  {len(test_pairs)}\")\n",
    "\n",
    "# Verify class balance\n",
    "for name, split in [('Train', train_pairs), ('Val', val_pairs), ('Test', test_pairs)]:\n",
    "    counts = {}\n",
    "    for p in split:\n",
    "        t = p['forgery_type']\n",
    "        counts[t] = counts.get(t, 0) + 1\n",
    "    total = len(split)\n",
    "    dist = ', '.join(f\"{t}: {c} ({100*c/total:.1f}%)\" for t, c in sorted(counts.items()))\n",
    "    print(f\"  {name}: {dist}\")"
]))

cells.append(code([
    "# ── Persist split manifest ───────────────────────────────────────────\n",
    "manifest = {\n",
    "    'seed': SEED,\n",
    "    'total_pairs': len(pairs),\n",
    "    'excluded_count': len(excluded),\n",
    "    'train': [p['image_path'] for p in train_pairs],\n",
    "    'val': [p['image_path'] for p in val_pairs],\n",
    "    'test': [p['image_path'] for p in test_pairs],\n",
    "}\n",
    "\n",
    "manifest_path = os.path.join(CONFIG['checkpoint_dir'], 'split_manifest.json')\n",
    "with open(manifest_path, 'w') as f:\n",
    "    json.dump(manifest, f, indent=2)\n",
    "print(f\"Split manifest saved to {manifest_path}\")"
]))

# ============================================================
# 4. DATASET CLASS & DATALOADERS
# ============================================================
cells.append(md([
    "---\n",
    "## 4. Dataset Class & DataLoaders\n",
    "\n",
    "PyTorch dataset with on-the-fly loading, mask binarization, and albumentations transforms.\n",
    "\n",
    "**MVP (Phase 1):** Spatial augmentations only — Resize, HorizontalFlip, VerticalFlip, RandomRotate90."
]))

cells.append(code([
    "# ── Dataset class ────────────────────────────────────────────────────\n",
    "class TamperingDataset(Dataset):\n",
    "    def __init__(self, pairs, transform=None, image_size=512):\n",
    "        self.pairs = pairs\n",
    "        self.transform = transform\n",
    "        self.image_size = image_size\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.pairs)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        entry = self.pairs[idx]\n",
    "\n",
    "        # Load image (BGR → RGB)\n",
    "        image = cv2.imread(entry['image_path'])\n",
    "        if image is None:\n",
    "            raise IOError(f\"Failed to load image: {entry['image_path']}\")\n",
    "        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "        # Load or generate mask\n",
    "        if entry['mask_path'] is not None:\n",
    "            mask = cv2.imread(entry['mask_path'], cv2.IMREAD_GRAYSCALE)\n",
    "            if mask is None:\n",
    "                raise IOError(f\"Failed to load mask: {entry['mask_path']}\")\n",
    "            mask = (mask > 128).astype(np.uint8)\n",
    "        else:\n",
    "            h, w = image.shape[:2]\n",
    "            mask = np.zeros((h, w), dtype=np.uint8)\n",
    "\n",
    "        # Apply transforms\n",
    "        if self.transform:\n",
    "            augmented = self.transform(image=image, mask=mask)\n",
    "            image = augmented['image']\n",
    "            mask = augmented['mask']\n",
    "        else:\n",
    "            # Fallback: manual resize + normalize\n",
    "            image = cv2.resize(image, (self.image_size, self.image_size))\n",
    "            mask = cv2.resize(mask, (self.image_size, self.image_size),\n",
    "                              interpolation=cv2.INTER_NEAREST)\n",
    "            image = image.astype(np.float32) / 255.0\n",
    "            mean = np.array([0.485, 0.456, 0.406])\n",
    "            std = np.array([0.229, 0.224, 0.225])\n",
    "            image = (image - mean) / std\n",
    "            image = torch.from_numpy(image.transpose(2, 0, 1)).float()\n",
    "            mask = torch.from_numpy(mask).float()\n",
    "\n",
    "        # Ensure mask shape: [1, H, W]\n",
    "        if isinstance(mask, torch.Tensor) and mask.dim() == 2:\n",
    "            mask = mask.unsqueeze(0).float()\n",
    "\n",
    "        label = torch.tensor(entry['label'], dtype=torch.float32)\n",
    "        return image, mask, label"
]))

cells.append(code([
    "# ── Transforms (Phase 1 MVP: spatial only) ──────────────────────────\n",
    "IMG_SIZE = CONFIG['image_size']\n",
    "\n",
    "train_transform = A.Compose([\n",
    "    A.Resize(IMG_SIZE, IMG_SIZE),\n",
    "    A.HorizontalFlip(p=0.5),\n",
    "    A.VerticalFlip(p=0.5),\n",
    "    A.RandomRotate90(p=0.5),\n",
    "    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),\n",
    "    ToTensorV2(),\n",
    "])\n",
    "\n",
    "val_transform = A.Compose([\n",
    "    A.Resize(IMG_SIZE, IMG_SIZE),\n",
    "    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),\n",
    "    ToTensorV2(),\n",
    "])\n",
    "\n",
    "print(\"Train transforms:\", train_transform)\n",
    "print(\"Val transforms:\", val_transform)"
]))

cells.append(code([
    "# ── DataLoaders ──────────────────────────────────────────────────────\n",
    "train_dataset = TamperingDataset(train_pairs, transform=train_transform, image_size=IMG_SIZE)\n",
    "val_dataset   = TamperingDataset(val_pairs,   transform=val_transform,   image_size=IMG_SIZE)\n",
    "test_dataset  = TamperingDataset(test_pairs,  transform=val_transform,   image_size=IMG_SIZE)\n",
    "\n",
    "train_loader = DataLoader(\n",
    "    train_dataset, batch_size=CONFIG['batch_size'], shuffle=True,\n",
    "    num_workers=CONFIG['num_workers'], pin_memory=True, drop_last=True,\n",
    ")\n",
    "val_loader = DataLoader(\n",
    "    val_dataset, batch_size=CONFIG['batch_size'], shuffle=False,\n",
    "    num_workers=CONFIG['num_workers'], pin_memory=True, drop_last=False,\n",
    ")\n",
    "test_loader = DataLoader(\n",
    "    test_dataset, batch_size=CONFIG['batch_size'], shuffle=False,\n",
    "    num_workers=CONFIG['num_workers'], pin_memory=True, drop_last=False,\n",
    ")\n",
    "\n",
    "print(f\"Train batches: {len(train_loader)} (drop_last=True)\")\n",
    "print(f\"Val batches:   {len(val_loader)}\")\n",
    "print(f\"Test batches:  {len(test_loader)}\")"
]))

cells.append(code([
    "# ── Sanity check: visualize one batch ────────────────────────────────\n",
    "images, masks, labels = next(iter(train_loader))\n",
    "print(f\"Image batch: {images.shape}, dtype={images.dtype}\")\n",
    "print(f\"Mask batch:  {masks.shape}, dtype={masks.dtype}\")\n",
    "print(f\"Labels:      {labels}\")\n",
    "\n",
    "fig, axes = plt.subplots(2, 4, figsize=(16, 8))\n",
    "mean = np.array([0.485, 0.456, 0.406])\n",
    "std = np.array([0.229, 0.224, 0.225])\n",
    "\n",
    "for i in range(min(4, images.shape[0])):\n",
    "    img = images[i].permute(1, 2, 0).numpy()\n",
    "    img = (img * std + mean).clip(0, 1)\n",
    "    msk = masks[i, 0].numpy()\n",
    "\n",
    "    axes[0, i].imshow(img)\n",
    "    axes[0, i].set_title(f\"Image (label={labels[i]:.0f})\")\n",
    "    axes[0, i].axis('off')\n",
    "\n",
    "    axes[1, i].imshow(msk, cmap='gray', vmin=0, vmax=1)\n",
    "    axes[1, i].set_title('Mask')\n",
    "    axes[1, i].axis('off')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
]))

# ============================================================
# 5. MODEL
# ============================================================
cells.append(md([
    "---\n",
    "## 5. Model Definition\n",
    "\n",
    "U-Net with pretrained ResNet34 encoder via `segmentation_models_pytorch`.\n",
    "\n",
    "- Output: raw logits `(B, 1, 512, 512)` — sigmoid during inference only\n",
    "- Image-level detection: `max(prob_map) >= threshold` (locked for MVP)\n",
    "- SMP API: use `model.encoder`, `model.decoder`, `model.segmentation_head` directly"
]))

cells.append(code([
    "# ── Model ────────────────────────────────────────────────────────────\n",
    "model = smp.Unet(\n",
    "    encoder_name=CONFIG['encoder_name'],\n",
    "    encoder_weights=CONFIG['encoder_weights'],\n",
    "    in_channels=CONFIG['in_channels'],\n",
    "    classes=CONFIG['classes'],\n",
    "    activation=None,\n",
    ")\n",
    "model = model.to(device)\n",
    "\n",
    "total_params = sum(p.numel() for p in model.parameters())\n",
    "trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
    "print(f\"Total parameters:     {total_params:,}\")\n",
    "print(f\"Trainable parameters: {trainable_params:,}\")\n",
    "\n",
    "# Quick forward pass check\n",
    "with torch.no_grad():\n",
    "    dummy = torch.randn(1, 3, IMG_SIZE, IMG_SIZE, device=device)\n",
    "    out = model(dummy)\n",
    "    print(f\"Output shape: {out.shape}\")  # Expected: (1, 1, 512, 512)"
]))

# ============================================================
# 6. LOSS & OPTIMIZER
# ============================================================
cells.append(md([
    "---\n",
    "## 6. Loss Function & Optimizer\n",
    "\n",
    "- **Loss:** BCE + Dice — handles class imbalance (typically <5% tampered pixels)\n",
    "- **Optimizer:** AdamW with differential LR (encoder 1e-4, decoder/head 1e-3)\n",
    "- **AMP:** Mixed precision for VRAM efficiency"
]))

cells.append(code([
    "# ── Loss function ────────────────────────────────────────────────────\n",
    "class BCEDiceLoss(nn.Module):\n",
    "    def __init__(self, smooth=1.0):\n",
    "        super().__init__()\n",
    "        self.bce = nn.BCEWithLogitsLoss()\n",
    "        self.smooth = smooth\n",
    "\n",
    "    def forward(self, logits, targets):\n",
    "        bce_loss = self.bce(logits, targets)\n",
    "        probs = torch.sigmoid(logits)\n",
    "        intersection = (probs * targets).sum()\n",
    "        dice_loss = 1.0 - (2.0 * intersection + self.smooth) / (\n",
    "            probs.sum() + targets.sum() + self.smooth\n",
    "        )\n",
    "        return bce_loss + dice_loss\n",
    "\n",
    "\n",
    "criterion = BCEDiceLoss().to(device)\n",
    "print(\"Loss: BCEWithLogitsLoss + DiceLoss (equal weight, smooth=1.0)\")"
]))

cells.append(code([
    "# ── Optimizer & AMP ──────────────────────────────────────────────────\n",
    "optimizer = torch.optim.AdamW([\n",
    "    {'params': model.encoder.parameters(),          'lr': CONFIG['encoder_lr']},\n",
    "    {'params': model.decoder.parameters(),          'lr': CONFIG['decoder_lr']},\n",
    "    {'params': model.segmentation_head.parameters(), 'lr': CONFIG['decoder_lr']},\n",
    "], weight_decay=CONFIG['weight_decay'])\n",
    "\n",
    "scaler = GradScaler('cuda')\n",
    "\n",
    "print(f\"Optimizer: AdamW\")\n",
    "print(f\"  Encoder LR: {CONFIG['encoder_lr']}\")\n",
    "print(f\"  Decoder LR: {CONFIG['decoder_lr']}\")\n",
    "print(f\"  Weight decay: {CONFIG['weight_decay']}\")\n",
    "print(f\"  Effective batch: {CONFIG['batch_size'] * CONFIG['accumulation_steps']}\")"
]))

# ============================================================
# 7. METRICS
# ============================================================
cells.append(md([
    "---\n",
    "## 7. Evaluation Metrics\n",
    "\n",
    "Pixel-level: F1 (primary), IoU, Precision, Recall\n",
    "\n",
    "Image-level: Accuracy (via `max(prob_map) >= threshold`), AUC-ROC"
]))

cells.append(code([
    "# ── Metric functions ─────────────────────────────────────────────────\n",
    "def compute_pixel_f1(pred, gt, eps=1e-8):\n",
    "    \"\"\"Pixel-level F1 for a single sample.\"\"\"\n",
    "    pred, gt = pred.flatten(), gt.flatten()\n",
    "    if gt.sum() == 0 and pred.sum() == 0:\n",
    "        return 1.0\n",
    "    if gt.sum() == 0 and pred.sum() > 0:\n",
    "        return 0.0\n",
    "    tp = (pred * gt).sum()\n",
    "    fp = (pred * (1 - gt)).sum()\n",
    "    fn = ((1 - pred) * gt).sum()\n",
    "    precision = tp / (tp + fp + eps)\n",
    "    recall = tp / (tp + fn + eps)\n",
    "    return (2 * precision * recall / (precision + recall + eps)).item()\n",
    "\n",
    "\n",
    "def compute_iou(pred, gt, eps=1e-8):\n",
    "    \"\"\"Pixel-level IoU for a single sample.\"\"\"\n",
    "    pred, gt = pred.flatten(), gt.flatten()\n",
    "    if gt.sum() == 0 and pred.sum() == 0:\n",
    "        return 1.0\n",
    "    intersection = (pred * gt).sum()\n",
    "    union = pred.sum() + gt.sum() - intersection\n",
    "    if union == 0:\n",
    "        return 1.0\n",
    "    return (intersection / (union + eps)).item()\n",
    "\n",
    "\n",
    "def compute_precision_recall(pred, gt, eps=1e-8):\n",
    "    \"\"\"Pixel-level precision and recall.\"\"\"\n",
    "    pred, gt = pred.flatten(), gt.flatten()\n",
    "    tp = (pred * gt).sum()\n",
    "    fp = (pred * (1 - gt)).sum()\n",
    "    fn = ((1 - pred) * gt).sum()\n",
    "    return (tp / (tp + fp + eps)).item(), (tp / (tp + fn + eps)).item()\n",
    "\n",
    "\n",
    "def compute_image_accuracy(scores, labels, threshold=0.5):\n",
    "    preds = (np.array(scores) >= threshold).astype(int)\n",
    "    return (preds == np.array(labels)).mean()\n",
    "\n",
    "\n",
    "def compute_image_auc(scores, labels):\n",
    "    return roc_auc_score(labels, scores)\n",
    "\n",
    "\n",
    "print(\"Metrics defined: Pixel-F1, IoU, Precision, Recall, Image Accuracy, Image AUC-ROC\")"
]))

# ============================================================
# 8. TRAINING LOOP
# ============================================================
cells.append(md([
    "---\n",
    "## 8. Training Loop\n",
    "\n",
    "- AMP mixed precision\n",
    "- Gradient accumulation (4 steps → effective batch 16)\n",
    "- **Partial window flush** after final batch (v3 fix)\n",
    "- Early stopping on validation Pixel-F1 (patience=10)\n",
    "- Checkpoints: `best_model.pt`, `last_checkpoint.pt`, periodic every 10 epochs"
]))

cells.append(code([
    "# ── Checkpoint helpers ────────────────────────────────────────────────\n",
    "def save_checkpoint(state, is_best, checkpoint_dir, epoch):\n",
    "    os.makedirs(checkpoint_dir, exist_ok=True)\n",
    "    last_path = os.path.join(checkpoint_dir, 'last_checkpoint.pt')\n",
    "    torch.save(state, last_path)\n",
    "    if is_best:\n",
    "        best_path = os.path.join(checkpoint_dir, 'best_model.pt')\n",
    "        torch.save(state, best_path)\n",
    "    if (epoch + 1) % 10 == 0:\n",
    "        periodic_path = os.path.join(checkpoint_dir, f'checkpoint_epoch_{epoch + 1}.pt')\n",
    "        torch.save(state, periodic_path)\n",
    "\n",
    "\n",
    "def load_checkpoint(filepath, model, optimizer, scaler):\n",
    "    ckpt = torch.load(filepath, map_location=device, weights_only=False)\n",
    "    model.load_state_dict(ckpt['model_state_dict'])\n",
    "    optimizer.load_state_dict(ckpt['optimizer_state_dict'])\n",
    "    scaler.load_state_dict(ckpt['scaler_state_dict'])\n",
    "    return ckpt['epoch'] + 1, ckpt['best_f1'], ckpt['best_epoch']\n",
    "\n",
    "\n",
    "print(\"Checkpoint helpers defined.\")"
]))

cells.append(code([
    "# ── Validation function ──────────────────────────────────────────────\n",
    "@torch.no_grad()\n",
    "def validate(model, loader, criterion, device, threshold=0.5):\n",
    "    model.eval()\n",
    "    total_loss = 0.0\n",
    "    f1_scores, iou_scores = [], []\n",
    "\n",
    "    for images, masks, labels in loader:\n",
    "        images, masks = images.to(device), masks.to(device)\n",
    "        with autocast('cuda'):\n",
    "            logits = model(images)\n",
    "            loss = criterion(logits, masks)\n",
    "        total_loss += loss.item()\n",
    "        probs = torch.sigmoid(logits)\n",
    "        preds = (probs > threshold).float()\n",
    "        for pred, gt in zip(preds, masks):\n",
    "            f1_scores.append(compute_pixel_f1(pred, gt))\n",
    "            iou_scores.append(compute_iou(pred, gt))\n",
    "\n",
    "    return total_loss / len(loader), np.mean(f1_scores), np.mean(iou_scores)"
]))

cells.append(code([
    "# ── Training loop ────────────────────────────────────────────────────\n",
    "ACCUMULATION_STEPS = CONFIG['accumulation_steps']\n",
    "MAX_EPOCHS = CONFIG['max_epochs']\n",
    "PATIENCE = CONFIG['patience']\n",
    "CHECKPOINT_DIR = CONFIG['checkpoint_dir']\n",
    "\n",
    "# Resume support\n",
    "start_epoch = 0\n",
    "best_f1 = 0.0\n",
    "best_epoch = 0\n",
    "\n",
    "resume_path = os.path.join(CHECKPOINT_DIR, 'last_checkpoint.pt')\n",
    "if os.path.exists(resume_path):\n",
    "    print(f\"Resuming from {resume_path}\")\n",
    "    start_epoch, best_f1, best_epoch = load_checkpoint(resume_path, model, optimizer, scaler)\n",
    "    print(f\"  Epoch {start_epoch}, best F1={best_f1:.4f} (epoch {best_epoch})\")\n",
    "\n",
    "history = {'train_loss': [], 'val_loss': [], 'val_f1': [], 'val_iou': []}\n",
    "\n",
    "print(f\"\\nTraining from epoch {start_epoch}...\")\n",
    "print(f\"  Max epochs: {MAX_EPOCHS}, Patience: {PATIENCE}\")\n",
    "print(f\"  Accumulation: {ACCUMULATION_STEPS}, Checkpoints: {CHECKPOINT_DIR}\\n\")\n",
    "\n",
    "for epoch in range(start_epoch, MAX_EPOCHS):\n",
    "    model.train()\n",
    "    optimizer.zero_grad(set_to_none=True)\n",
    "    epoch_loss = 0.0\n",
    "\n",
    "    pbar = tqdm(train_loader, desc=f'Epoch {epoch+1}/{MAX_EPOCHS}')\n",
    "    for batch_idx, (images, masks, labels) in enumerate(pbar):\n",
    "        images, masks = images.to(device), masks.to(device)\n",
    "\n",
    "        with autocast('cuda'):\n",
    "            logits = model(images)\n",
    "            loss = criterion(logits, masks) / ACCUMULATION_STEPS\n",
    "\n",
    "        scaler.scale(loss).backward()\n",
    "\n",
    "        if (batch_idx + 1) % ACCUMULATION_STEPS == 0:\n",
    "            scaler.unscale_(optimizer)\n",
    "            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=CONFIG['max_grad_norm'])\n",
    "            scaler.step(optimizer)\n",
    "            scaler.update()\n",
    "            optimizer.zero_grad(set_to_none=True)\n",
    "\n",
    "        epoch_loss += loss.item() * ACCUMULATION_STEPS\n",
    "        pbar.set_postfix({'loss': f'{loss.item() * ACCUMULATION_STEPS:.4f}'})\n",
    "\n",
    "    # Flush remaining accumulated gradients (partial final window)\n",
    "    if (batch_idx + 1) % ACCUMULATION_STEPS != 0:\n",
    "        scaler.unscale_(optimizer)\n",
    "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=CONFIG['max_grad_norm'])\n",
    "        scaler.step(optimizer)\n",
    "        scaler.update()\n",
    "        optimizer.zero_grad(set_to_none=True)\n",
    "\n",
    "    avg_train_loss = epoch_loss / len(train_loader)\n",
    "\n",
    "    # Validation\n",
    "    val_loss, val_f1, val_iou = validate(model, val_loader, criterion, device)\n",
    "\n",
    "    history['train_loss'].append(avg_train_loss)\n",
    "    history['val_loss'].append(val_loss)\n",
    "    history['val_f1'].append(val_f1)\n",
    "    history['val_iou'].append(val_iou)\n",
    "\n",
    "    is_best = val_f1 > best_f1\n",
    "    if is_best:\n",
    "        best_f1 = val_f1\n",
    "        best_epoch = epoch\n",
    "\n",
    "    save_checkpoint({\n",
    "        'epoch': epoch,\n",
    "        'model_state_dict': model.state_dict(),\n",
    "        'optimizer_state_dict': optimizer.state_dict(),\n",
    "        'scaler_state_dict': scaler.state_dict(),\n",
    "        'best_f1': best_f1,\n",
    "        'best_epoch': best_epoch,\n",
    "        'train_loss': avg_train_loss,\n",
    "        'val_loss': val_loss,\n",
    "        'val_f1': val_f1,\n",
    "    }, is_best, CHECKPOINT_DIR, epoch)\n",
    "\n",
    "    marker = ' ★' if is_best else ''\n",
    "    print(f\"  Epoch {epoch+1}: train={avg_train_loss:.4f} | \"\n",
    "          f\"val={val_loss:.4f} | F1={val_f1:.4f} | IoU={val_iou:.4f}{marker}\")\n",
    "\n",
    "    # Early stopping\n",
    "    if epoch - best_epoch >= PATIENCE:\n",
    "        print(f\"\\nEarly stopping at epoch {epoch+1} (no improvement for {PATIENCE} epochs)\")\n",
    "        break\n",
    "\n",
    "print(f\"\\nTraining complete. Best F1={best_f1:.4f} at epoch {best_epoch+1}\")"
]))

# ============================================================
# 9. THRESHOLD SELECTION
# ============================================================
cells.append(md([
    "---\n",
    "## 9. Threshold Selection\n",
    "\n",
    "Sweep thresholds on **validation set** to find the operating point that maximizes mean Pixel-F1.\n",
    "\n",
    "This single threshold is used for both pixel-level binarization and image-level detection."
]))

cells.append(code([
    "# ── Load best model ──────────────────────────────────────────────────\n",
    "best_path = os.path.join(CHECKPOINT_DIR, 'best_model.pt')\n",
    "if os.path.exists(best_path):\n",
    "    ckpt = torch.load(best_path, map_location=device, weights_only=False)\n",
    "    model.load_state_dict(ckpt['model_state_dict'])\n",
    "    print(f\"Loaded best model from epoch {ckpt['epoch']+1} (F1={ckpt['best_f1']:.4f})\")\n",
    "else:\n",
    "    print(\"No best_model.pt found — using current model weights.\")"
]))

cells.append(code([
    "# ── Threshold search ─────────────────────────────────────────────────\n",
    "def find_best_threshold(model, loader, device, n_thresholds=50):\n",
    "    model.eval()\n",
    "    thresholds = np.linspace(0.1, 0.9, n_thresholds)\n",
    "\n",
    "    all_probs, all_masks = [], []\n",
    "    with torch.no_grad():\n",
    "        for images, masks, _ in tqdm(loader, desc='Collecting predictions'):\n",
    "            images = images.to(device)\n",
    "            with autocast('cuda'):\n",
    "                logits = model(images)\n",
    "            all_probs.append(torch.sigmoid(logits).cpu())\n",
    "            all_masks.append(masks)\n",
    "\n",
    "    all_probs = torch.cat(all_probs, dim=0)\n",
    "    all_masks = torch.cat(all_masks, dim=0)\n",
    "\n",
    "    best_t, best_f1 = 0.5, 0.0\n",
    "    f1_per_threshold = []\n",
    "\n",
    "    for t in thresholds:\n",
    "        preds = (all_probs > t).float()\n",
    "        f1s = [compute_pixel_f1(p, g) for p, g in zip(preds, all_masks)]\n",
    "        mean_f1 = np.mean(f1s)\n",
    "        f1_per_threshold.append(mean_f1)\n",
    "        if mean_f1 > best_f1:\n",
    "            best_f1 = mean_f1\n",
    "            best_t = t\n",
    "\n",
    "    return best_t, best_f1, thresholds, f1_per_threshold\n",
    "\n",
    "\n",
    "best_threshold, best_val_f1, thresholds_arr, f1_per_threshold = find_best_threshold(\n",
    "    model, val_loader, device, n_thresholds=CONFIG['n_threshold_search']\n",
    ")\n",
    "print(f\"\\nBest threshold: {best_threshold:.3f} (val F1={best_val_f1:.4f})\")"
]))

# ============================================================
# 10. EVALUATION
# ============================================================
cells.append(md([
    "---\n",
    "## 10. Evaluation on Test Set\n",
    "\n",
    "Report **mixed-set** (all images), **tampered-only**, and **forgery-type breakdown**."
]))

cells.append(code([
    "# ── Full evaluation ──────────────────────────────────────────────────\n",
    "def evaluate(model, loader, device, threshold):\n",
    "    \"\"\"Evaluate with a single threshold for both pixel and image-level decisions.\"\"\"\n",
    "    model.eval()\n",
    "    all_f1, all_iou, tampered_f1, tampered_iou = [], [], [], []\n",
    "    precisions, recalls = [], []\n",
    "    image_scores, image_labels = [], []\n",
    "\n",
    "    with torch.no_grad():\n",
    "        for images, masks, labels in tqdm(loader, desc='Evaluating'):\n",
    "            images = images.to(device)\n",
    "            with autocast('cuda'):\n",
    "                logits = model(images)\n",
    "            probs = torch.sigmoid(logits).cpu()\n",
    "            preds = (probs > threshold).float()\n",
    "\n",
    "            for pred, gt, prob, label in zip(preds, masks, probs, labels):\n",
    "                f1 = compute_pixel_f1(pred, gt)\n",
    "                iou = compute_iou(pred, gt)\n",
    "                p, r = compute_precision_recall(pred, gt)\n",
    "\n",
    "                all_f1.append(f1)\n",
    "                all_iou.append(iou)\n",
    "                precisions.append(p)\n",
    "                recalls.append(r)\n",
    "\n",
    "                if label.item() == 1.0:\n",
    "                    tampered_f1.append(f1)\n",
    "                    tampered_iou.append(iou)\n",
    "\n",
    "                # Image-level: max probability as tamper score\n",
    "                image_scores.append(prob.max().item())\n",
    "                image_labels.append(int(label.item()))\n",
    "\n",
    "    return {\n",
    "        'pixel_f1_mean': np.mean(all_f1),\n",
    "        'pixel_f1_std': np.std(all_f1),\n",
    "        'pixel_iou_mean': np.mean(all_iou),\n",
    "        'pixel_iou_std': np.std(all_iou),\n",
    "        'tampered_f1_mean': np.mean(tampered_f1) if tampered_f1 else 0.0,\n",
    "        'tampered_f1_std': np.std(tampered_f1) if tampered_f1 else 0.0,\n",
    "        'tampered_iou_mean': np.mean(tampered_iou) if tampered_iou else 0.0,\n",
    "        'tampered_iou_std': np.std(tampered_iou) if tampered_iou else 0.0,\n",
    "        'precision_mean': np.mean(precisions),\n",
    "        'recall_mean': np.mean(recalls),\n",
    "        'image_accuracy': compute_image_accuracy(image_scores, image_labels, threshold),\n",
    "        'image_auc_roc': compute_image_auc(image_scores, image_labels),\n",
    "        'threshold_used': threshold,\n",
    "        'num_test_images': len(all_f1),\n",
    "        'num_tampered_images': len(tampered_f1),\n",
    "        '_image_scores': image_scores,\n",
    "        '_image_labels': image_labels,\n",
    "    }\n",
    "\n",
    "\n",
    "test_results = evaluate(model, test_loader, device, threshold=best_threshold)\n",
    "\n",
    "print(f\"\\n{'='*60}\")\n",
    "print(f\"TEST SET RESULTS (threshold={best_threshold:.3f})\")\n",
    "print(f\"{'='*60}\")\n",
    "print(f\"\")\n",
    "print(f\"Mixed-set ({test_results['num_test_images']} images):\")\n",
    "print(f\"  Pixel-F1:  {test_results['pixel_f1_mean']:.4f} ± {test_results['pixel_f1_std']:.4f}\")\n",
    "print(f\"  Pixel-IoU: {test_results['pixel_iou_mean']:.4f} ± {test_results['pixel_iou_std']:.4f}\")\n",
    "print(f\"  Precision: {test_results['precision_mean']:.4f}\")\n",
    "print(f\"  Recall:    {test_results['recall_mean']:.4f}\")\n",
    "print(f\"\")\n",
    "print(f\"Tampered-only ({test_results['num_tampered_images']} images):\")\n",
    "print(f\"  Pixel-F1:  {test_results['tampered_f1_mean']:.4f} ± {test_results['tampered_f1_std']:.4f}\")\n",
    "print(f\"  Pixel-IoU: {test_results['tampered_iou_mean']:.4f} ± {test_results['tampered_iou_std']:.4f}\")\n",
    "print(f\"\")\n",
    "print(f\"Image-level:\")\n",
    "print(f\"  Accuracy:  {test_results['image_accuracy']:.4f}\")\n",
    "print(f\"  AUC-ROC:   {test_results['image_auc_roc']:.4f}\")"
]))

cells.append(code([
    "# ── Forgery-type breakdown ───────────────────────────────────────────\n",
    "def eval_subset(model, pairs, device, threshold, transform):\n",
    "    dataset = TamperingDataset(pairs, transform=transform)\n",
    "    loader = DataLoader(dataset, batch_size=CONFIG['batch_size'],\n",
    "                       shuffle=False, num_workers=CONFIG['num_workers'])\n",
    "    f1s = []\n",
    "    model.eval()\n",
    "    with torch.no_grad():\n",
    "        for images, masks, _ in loader:\n",
    "            images = images.to(device)\n",
    "            with autocast('cuda'):\n",
    "                logits = model(images)\n",
    "            preds = (torch.sigmoid(logits).cpu() > threshold).float()\n",
    "            for pred, gt in zip(preds, masks):\n",
    "                f1s.append(compute_pixel_f1(pred, gt))\n",
    "    return np.mean(f1s), np.std(f1s)\n",
    "\n",
    "\n",
    "splicing_pairs = [p for p in test_pairs if p['forgery_type'] == 'splicing']\n",
    "copymove_pairs = [p for p in test_pairs if p['forgery_type'] == 'copy-move']\n",
    "\n",
    "print(f\"\\nForgery-type breakdown:\")\n",
    "if splicing_pairs:\n",
    "    sp_f1, sp_std = eval_subset(model, splicing_pairs, device, best_threshold, val_transform)\n",
    "    print(f\"  Splicing ({len(splicing_pairs)} images):  F1={sp_f1:.4f} ± {sp_std:.4f}\")\n",
    "if copymove_pairs:\n",
    "    cm_f1, cm_std = eval_subset(model, copymove_pairs, device, best_threshold, val_transform)\n",
    "    print(f\"  Copy-move ({len(copymove_pairs)} images): F1={cm_f1:.4f} ± {cm_std:.4f}\")"
]))

# ============================================================
# 11. VISUALIZATION
# ============================================================
cells.append(md([
    "---\n",
    "## 11. Visualization\n",
    "\n",
    "Training curves, F1-vs-threshold, and 4-column prediction grid."
]))

cells.append(code([
    "# ── Training curves ──────────────────────────────────────────────────\n",
    "fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n",
    "epochs_range = range(1, len(history['train_loss']) + 1)\n",
    "\n",
    "axes[0].plot(epochs_range, history['train_loss'], label='Train')\n",
    "axes[0].plot(epochs_range, history['val_loss'], label='Val')\n",
    "axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Loss')\n",
    "axes[0].set_title('Loss'); axes[0].legend(); axes[0].grid(True, alpha=0.3)\n",
    "\n",
    "axes[1].plot(epochs_range, history['val_f1'], color='green')\n",
    "axes[1].axvline(x=best_epoch + 1, color='red', linestyle='--', label=f'Best epoch {best_epoch+1}')\n",
    "axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Pixel-F1')\n",
    "axes[1].set_title('Validation Pixel-F1'); axes[1].legend(); axes[1].grid(True, alpha=0.3)\n",
    "\n",
    "axes[2].plot(epochs_range, history['val_iou'], color='orange')\n",
    "axes[2].set_xlabel('Epoch'); axes[2].set_ylabel('Pixel-IoU')\n",
    "axes[2].set_title('Validation Pixel-IoU'); axes[2].grid(True, alpha=0.3)\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.savefig('training_curves.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

cells.append(code([
    "# ── F1 vs Threshold ──────────────────────────────────────────────────\n",
    "fig, ax = plt.subplots(figsize=(8, 5))\n",
    "ax.plot(thresholds_arr, f1_per_threshold, 'b-', linewidth=2)\n",
    "ax.axvline(x=best_threshold, color='red', linestyle='--',\n",
    "           label=f'Best threshold={best_threshold:.3f}')\n",
    "ax.set_xlabel('Threshold'); ax.set_ylabel('Mean Pixel-F1 (Validation)')\n",
    "ax.set_title('Pixel-F1 vs. Threshold')\n",
    "ax.legend(); ax.grid(True, alpha=0.3)\n",
    "plt.tight_layout()\n",
    "plt.savefig('f1_vs_threshold.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

cells.append(code([
    "# ── Collect predictions for grid ─────────────────────────────────────\n",
    "def collect_predictions(model, loader, device, threshold):\n",
    "    model.eval()\n",
    "    results = []\n",
    "    with torch.no_grad():\n",
    "        for images, masks, labels in loader:\n",
    "            images_gpu = images.to(device)\n",
    "            with autocast('cuda'):\n",
    "                logits = model(images_gpu)\n",
    "            probs = torch.sigmoid(logits).cpu()\n",
    "            preds = (probs > threshold).float()\n",
    "            for i in range(images.shape[0]):\n",
    "                f1 = compute_pixel_f1(preds[i], masks[i])\n",
    "                results.append({\n",
    "                    'image': images[i], 'mask': masks[i], 'pred': preds[i],\n",
    "                    'prob': probs[i], 'label': labels[i].item(), 'f1': f1,\n",
    "                })\n",
    "    return results\n",
    "\n",
    "\n",
    "test_predictions = collect_predictions(model, test_loader, device, best_threshold)\n",
    "print(f\"Collected {len(test_predictions)} predictions\")"
]))

cells.append(code([
    "# ── Select representative samples ────────────────────────────────────\n",
    "tampered_preds = sorted(\n",
    "    [p for p in test_predictions if p['label'] == 1.0],\n",
    "    key=lambda x: x['f1'],\n",
    ")\n",
    "authentic_preds = [p for p in test_predictions if p['label'] == 0.0]\n",
    "\n",
    "n = len(tampered_preds)\n",
    "mid = n // 2\n",
    "selected = []\n",
    "if n >= 6:\n",
    "    selected += tampered_preds[-2:]          # best\n",
    "    selected += tampered_preds[mid-1:mid+1]  # median\n",
    "    selected += tampered_preds[:2]            # worst\n",
    "else:\n",
    "    selected += tampered_preds\n",
    "selected += authentic_preds[:2]\n",
    "\n",
    "print(f\"Selected {len(selected)} samples for prediction grid\")"
]))

cells.append(code([
    "# ── Prediction grid (4-column: Original | GT | Predicted | Overlay) ──\n",
    "n_samples = len(selected)\n",
    "fig, axes = plt.subplots(n_samples, 4, figsize=(16, 4 * n_samples))\n",
    "if n_samples == 1:\n",
    "    axes = axes.reshape(1, -1)\n",
    "\n",
    "mean = np.array([0.485, 0.456, 0.406])\n",
    "std = np.array([0.229, 0.224, 0.225])\n",
    "\n",
    "for i, sample in enumerate(selected):\n",
    "    img = sample['image'].permute(1, 2, 0).numpy()\n",
    "    img = (img * std + mean).clip(0, 1)\n",
    "    gt = sample['mask'][0].numpy()\n",
    "    pred = sample['pred'][0].numpy()\n",
    "    f1 = sample['f1']\n",
    "    lbl = 'tampered' if sample['label'] == 1.0 else 'authentic'\n",
    "\n",
    "    axes[i, 0].imshow(img)\n",
    "    axes[i, 0].set_title(f'Original ({lbl})')\n",
    "    axes[i, 0].axis('off')\n",
    "\n",
    "    axes[i, 1].imshow(gt, cmap='gray', vmin=0, vmax=1)\n",
    "    axes[i, 1].set_title('Ground Truth')\n",
    "    axes[i, 1].axis('off')\n",
    "\n",
    "    axes[i, 2].imshow(pred, cmap='gray', vmin=0, vmax=1)\n",
    "    axes[i, 2].set_title('Predicted Mask')\n",
    "    axes[i, 2].axis('off')\n",
    "\n",
    "    overlay = img.copy()\n",
    "    overlay[pred > 0] = overlay[pred > 0] * 0.6 + np.array([1, 0, 0]) * 0.4\n",
    "    axes[i, 3].imshow(overlay)\n",
    "    axes[i, 3].set_title(f'Overlay (F1={f1:.3f})')\n",
    "    axes[i, 3].axis('off')\n",
    "\n",
    "plt.suptitle(f'Prediction Results (threshold={best_threshold:.3f})', fontsize=14, y=1.01)\n",
    "plt.tight_layout()\n",
    "plt.savefig('prediction_grid.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ============================================================
# 12. ROBUSTNESS TESTING
# ============================================================
cells.append(md([
    "---\n",
    "## 12. Robustness Testing (Bonus — Phase 3)\n",
    "\n",
    "Test model under controlled degradations. Images are degraded; masks stay clean.\n",
    "Validation-selected threshold is reused — no per-degradation tuning.\n",
    "\n",
    "**v3 additions:** Gaussian blur, resize degradation (fully wired into eval loop)."
]))

cells.append(code([
    "# ── Robustness transforms (albumentations-based) ─────────────────────\n",
    "NORMALIZE = A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225))\n",
    "\n",
    "robustness_transforms = {\n",
    "    'clean': A.Compose([\n",
    "        A.Resize(IMG_SIZE, IMG_SIZE), NORMALIZE, ToTensorV2(),\n",
    "    ]),\n",
    "    'jpeg_qf70': A.Compose([\n",
    "        A.Resize(IMG_SIZE, IMG_SIZE),\n",
    "        A.ImageCompression(quality_lower=70, quality_upper=70, p=1.0),\n",
    "        NORMALIZE, ToTensorV2(),\n",
    "    ]),\n",
    "    'jpeg_qf50': A.Compose([\n",
    "        A.Resize(IMG_SIZE, IMG_SIZE),\n",
    "        A.ImageCompression(quality_lower=50, quality_upper=50, p=1.0),\n",
    "        NORMALIZE, ToTensorV2(),\n",
    "    ]),\n",
    "    'gaussian_noise_light': A.Compose([\n",
    "        A.Resize(IMG_SIZE, IMG_SIZE),\n",
    "        A.GaussNoise(var_limit=(10.0, 50.0), p=1.0),\n",
    "        NORMALIZE, ToTensorV2(),\n",
    "    ]),\n",
    "    'gaussian_noise_heavy': A.Compose([\n",
    "        A.Resize(IMG_SIZE, IMG_SIZE),\n",
    "        A.GaussNoise(var_limit=(100.0, 100.0), p=1.0),\n",
    "        NORMALIZE, ToTensorV2(),\n",
    "    ]),\n",
    "    'gaussian_blur': A.Compose([\n",
    "        A.Resize(IMG_SIZE, IMG_SIZE),\n",
    "        A.GaussianBlur(blur_limit=(5, 5), p=1.0),\n",
    "        NORMALIZE, ToTensorV2(),\n",
    "    ]),\n",
    "}\n",
    "\n",
    "print(f\"Albumentations-based degradations: {list(robustness_transforms.keys())}\")"
]))

cells.append(code([
    "# ── Resize degradation dataset (image-only, masks clean) ─────────────\n",
    "class ResizeDegradationDataset(Dataset):\n",
    "    \"\"\"Apply resize degradation to images only; masks follow the clean path.\"\"\"\n",
    "\n",
    "    def __init__(self, pairs, scale_factor, image_size=512):\n",
    "        self.pairs = pairs\n",
    "        self.scale_factor = scale_factor\n",
    "        self.image_size = image_size\n",
    "        self.normalize = A.Compose([\n",
    "            A.Resize(image_size, image_size),\n",
    "            A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),\n",
    "            ToTensorV2(),\n",
    "        ])\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.pairs)\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        entry = self.pairs[idx]\n",
    "\n",
    "        image = cv2.imread(entry['image_path'])\n",
    "        if image is None:\n",
    "            raise IOError(f\"Failed to load: {entry['image_path']}\")\n",
    "        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)\n",
    "\n",
    "        # Resize degradation: downscale then restore to original size\n",
    "        h, w = image.shape[:2]\n",
    "        small_h, small_w = max(1, int(h * self.scale_factor)), max(1, int(w * self.scale_factor))\n",
    "        degraded = cv2.resize(image, (small_w, small_h), interpolation=cv2.INTER_LINEAR)\n",
    "        degraded = cv2.resize(degraded, (w, h), interpolation=cv2.INTER_LINEAR)\n",
    "\n",
    "        # Mask: clean path\n",
    "        if entry['mask_path'] is not None:\n",
    "            mask = cv2.imread(entry['mask_path'], cv2.IMREAD_GRAYSCALE)\n",
    "            mask = (mask > 128).astype(np.uint8)\n",
    "        else:\n",
    "            mask = np.zeros((h, w), dtype=np.uint8)\n",
    "\n",
    "        augmented = self.normalize(image=degraded, mask=mask)\n",
    "        image_t = augmented['image']\n",
    "        mask_t = augmented['mask'].unsqueeze(0).float()\n",
    "        label = torch.tensor(entry['label'], dtype=torch.float32)\n",
    "        return image_t, mask_t, label\n",
    "\n",
    "\n",
    "print(\"ResizeDegradationDataset defined.\")"
]))

cells.append(code([
    "# ── Robustness evaluation loop ───────────────────────────────────────\n",
    "def run_eval_loop(model, loader, device, threshold):\n",
    "    \"\"\"Run evaluation and return per-image F1 scores.\"\"\"\n",
    "    model.eval()\n",
    "    f1_scores = []\n",
    "    with torch.no_grad():\n",
    "        for images, masks, _ in loader:\n",
    "            images = images.to(device)\n",
    "            with autocast('cuda'):\n",
    "                logits = model(images)\n",
    "            preds = (torch.sigmoid(logits).cpu() > threshold).float()\n",
    "            for pred, gt in zip(preds, masks):\n",
    "                f1_scores.append(compute_pixel_f1(pred, gt))\n",
    "    return f1_scores\n",
    "\n",
    "\n",
    "def evaluate_robustness(model, test_pairs, device, threshold, transforms_dict, resize_scales):\n",
    "    results = {}\n",
    "    BS = CONFIG['batch_size']\n",
    "    NW = CONFIG['num_workers']\n",
    "\n",
    "    # Albumentations-based degradations\n",
    "    for name, transform in transforms_dict.items():\n",
    "        dataset = TamperingDataset(test_pairs, transform=transform)\n",
    "        loader = DataLoader(dataset, batch_size=BS, shuffle=False, num_workers=NW)\n",
    "        f1s = run_eval_loop(model, loader, device, threshold)\n",
    "        results[name] = {'f1_mean': np.mean(f1s), 'f1_std': np.std(f1s)}\n",
    "        print(f\"  {name}: F1={results[name]['f1_mean']:.4f} ± {results[name]['f1_std']:.4f}\")\n",
    "\n",
    "    # Resize degradations\n",
    "    for scale in resize_scales:\n",
    "        dataset = ResizeDegradationDataset(test_pairs, scale_factor=scale)\n",
    "        loader = DataLoader(dataset, batch_size=BS, shuffle=False, num_workers=NW)\n",
    "        f1s = run_eval_loop(model, loader, device, threshold)\n",
    "        name = f'resize_{scale}x'\n",
    "        results[name] = {'f1_mean': np.mean(f1s), 'f1_std': np.std(f1s)}\n",
    "        print(f\"  {name}: F1={results[name]['f1_mean']:.4f} ± {results[name]['f1_std']:.4f}\")\n",
    "\n",
    "    return results\n",
    "\n",
    "\n",
    "print(f\"\\nRunning robustness evaluation (threshold={best_threshold:.3f})...\")\n",
    "robustness_results = evaluate_robustness(\n",
    "    model, test_pairs, device, best_threshold,\n",
    "    robustness_transforms,\n",
    "    resize_scales=[0.75, 0.5],\n",
    ")"
]))

cells.append(code([
    "# ── Robustness table & chart ─────────────────────────────────────────\n",
    "clean_f1 = robustness_results['clean']['f1_mean']\n",
    "\n",
    "print(f\"\\n{'Degradation':<25} {'Pixel-F1 (mean ± std)':<25} {'Δ from clean':>12}\")\n",
    "print('-' * 65)\n",
    "for name, res in robustness_results.items():\n",
    "    delta = res['f1_mean'] - clean_f1\n",
    "    delta_str = '—' if name == 'clean' else f\"{delta:+.4f}\"\n",
    "    print(f\"{name:<25} {res['f1_mean']:.4f} ± {res['f1_std']:.4f}        {delta_str:>12}\")\n",
    "\n",
    "# Bar chart\n",
    "fig, ax = plt.subplots(figsize=(12, 5))\n",
    "names = list(robustness_results.keys())\n",
    "means = [robustness_results[n]['f1_mean'] for n in names]\n",
    "stds = [robustness_results[n]['f1_std'] for n in names]\n",
    "colors = ['green' if n == 'clean' else 'steelblue' for n in names]\n",
    "\n",
    "ax.bar(names, means, yerr=stds, capsize=5, color=colors, alpha=0.8)\n",
    "ax.set_ylabel('Mean Pixel-F1')\n",
    "ax.set_title('Robustness: Pixel-F1 Under Degradations')\n",
    "ax.set_ylim(0, 1)\n",
    "ax.grid(True, alpha=0.3, axis='y')\n",
    "plt.xticks(rotation=35, ha='right')\n",
    "plt.tight_layout()\n",
    "plt.savefig('robustness_chart.png', dpi=150, bbox_inches='tight')\n",
    "plt.show()"
]))

# ============================================================
# 13. EXPERIMENT TRACKING (W&B)
# ============================================================
cells.append(md([
    "---\n",
    "## 13. Experiment Tracking (Optional — W&B)\n",
    "\n",
    "W&B integration for logging metrics, comparing runs, and storing artifacts.\n",
    "\n",
    "**This section is optional.** All cells are guarded — the notebook works without W&B."
]))

cells.append(code([
    "# ── W&B setup (optional) ─────────────────────────────────────────────\n",
    "USE_WANDB = False\n",
    "try:\n",
    "    import wandb\n",
    "    USE_WANDB = True\n",
    "    print(\"W&B available. Set USE_WANDB = True above to enable.\")\n",
    "except ImportError:\n",
    "    print(\"W&B not installed. Run: pip install wandb\")\n",
    "    print(\"Notebook will work without it.\")"
]))

cells.append(code([
    "# ── Log experiment results to W&B ────────────────────────────────────\n",
    "if USE_WANDB:\n",
    "    wandb.login()\n",
    "    run = wandb.init(\n",
    "        project=\"tamper-detection\",\n",
    "        config=CONFIG,\n",
    "        name=f\"unet-resnet34-seed{SEED}\",\n",
    "        tags=[\"v3\", \"casia-v2\", \"mvp\"],\n",
    "    )\n",
    "\n",
    "    # Log training history\n",
    "    for i in range(len(history['train_loss'])):\n",
    "        wandb.log({\n",
    "            'epoch': i + 1,\n",
    "            'train/loss': history['train_loss'][i],\n",
    "            'val/loss': history['val_loss'][i],\n",
    "            'val/pixel_f1': history['val_f1'][i],\n",
    "            'val/pixel_iou': history['val_iou'][i],\n",
    "        })\n",
    "\n",
    "    # Log test results\n",
    "    wandb.summary.update({\n",
    "        'best/val_f1': best_f1,\n",
    "        'best/epoch': best_epoch + 1,\n",
    "        'test/pixel_f1_mixed': test_results['pixel_f1_mean'],\n",
    "        'test/pixel_f1_tampered': test_results['tampered_f1_mean'],\n",
    "        'test/pixel_iou_mixed': test_results['pixel_iou_mean'],\n",
    "        'test/image_accuracy': test_results['image_accuracy'],\n",
    "        'test/image_auc_roc': test_results['image_auc_roc'],\n",
    "        'test/threshold': best_threshold,\n",
    "    })\n",
    "\n",
    "    # Log visualizations\n",
    "    for fname in ['training_curves.png', 'prediction_grid.png', 'f1_vs_threshold.png', 'robustness_chart.png']:\n",
    "        if os.path.exists(fname):\n",
    "            wandb.log({fname.replace('.png', ''): wandb.Image(fname)})\n",
    "\n",
    "    # Log best model artifact\n",
    "    best_pt = os.path.join(CHECKPOINT_DIR, 'best_model.pt')\n",
    "    if os.path.exists(best_pt):\n",
    "        artifact = wandb.Artifact('best-model', type='model')\n",
    "        artifact.add_file(best_pt)\n",
    "        wandb.log_artifact(artifact)\n",
    "\n",
    "    wandb.finish()\n",
    "    print(\"W&B run logged and finished.\")\n",
    "else:\n",
    "    print(\"W&B disabled — skipping experiment logging.\")"
]))

# ============================================================
# 14. SAVE & EXPORT
# ============================================================
cells.append(md([
    "---\n",
    "## 14. Save & Export\n",
    "\n",
    "Persist results summary and final checkpoint information."
]))

cells.append(code([
    "# ── Save results summary ─────────────────────────────────────────────\n",
    "results_summary = {\n",
    "    'version': 'v3',\n",
    "    'threshold': best_threshold,\n",
    "    'test_results': {k: v for k, v in test_results.items() if not k.startswith('_')},\n",
    "    'training_epochs': len(history['train_loss']),\n",
    "    'best_epoch': best_epoch + 1,\n",
    "    'config': CONFIG,\n",
    "}\n",
    "\n",
    "# Add robustness results if available\n",
    "if 'robustness_results' in dir():\n",
    "    results_summary['robustness'] = {\n",
    "        k: v for k, v in robustness_results.items()\n",
    "    }\n",
    "\n",
    "summary_path = os.path.join(CHECKPOINT_DIR, 'results_summary_v3.json')\n",
    "with open(summary_path, 'w') as f:\n",
    "    json.dump(results_summary, f, indent=2, default=str)\n",
    "\n",
    "print(f\"Results saved to {summary_path}\")\n",
    "print(f\"Best model: {os.path.join(CHECKPOINT_DIR, 'best_model.pt')}\")\n",
    "print(f\"\\nNotebook complete!\")"
]))

# ============================================================
# BUILD NOTEBOOK JSON
# ============================================================
notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {"provenance": [], "gpuType": "T4"},
        "kernelspec": {"name": "python3", "display_name": "Python 3"},
        "language_info": {"name": "python"},
        "accelerator": "GPU",
    },
    "cells": cells,
}

output_path = r"C:\D Drive\Projects\BigVision Assignment\notebooks\tamper_detection_v3.ipynb"
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"Notebook v3 created with {len(cells)} cells at {output_path}")
